name: studentmanagement_week
description: Ứng dụng điểm danh sinh viên bằng QR
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

  # QR Code
  qr_flutter: ^4.1.0 
  mobile_scanner: ^5.2.3 

  # UI & Hiệu ứng
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  flutter_svg: ^2.0.10
  glassmorphism: ^3.0.0
  animated_splash_screen: ^1.3.0

  # Utils
  shared_preferences: ^2.3.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
